services:
  api:
    build: ./api
    restart: unless-stopped
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_ADMIN_PASSWORD=$MYSQLDB_ADMIN_PASSWORD
      - DB_CLIENT_PASSWORD=$MYSQLDB_CLIENT_PASSWORD
      - DB_ATC_PASSWORD=$MYSQLDB_ATC_PASSWORD
      - DB_GROUND_CREW_PASSWORD=$MYSQLDB_GROUND_CREW_PASSWORD
      - DB_AIRPORT_STAFF_PASSWORD=$MYSQLDB_AIRPORT_STAFF_PASSWORD
      - DB_PARKING_STAFF_PASSWORD=$MYSQLDB_PARKING_STAFF_PASSWORD
      - DB_RENTAL_STAFF_PASSWORD=$MYSQLDB_RENTAL_STAFF_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    volumes:
      - ./api/files:/api/files
  ui:
    build: ./ui
    depends_on:
      - api
    environment:
      - TZ=Europe/Warsaw
      - REACT_DOCKER_PORT=$REACT_DOCKER_PORT
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
