services:
  mysqldb:
    env_file: ./.env.prod
  api:
    env_file: ./.env.prod
  ui:
    build: 
      context: ./ui
      target: production
    env_file: ./.env.prod
    volumes:
      - ./ui:/test